-- ЕДИНЫЙ SQL ДЛЯ tgk_bd (создание + обновление до текущей версии)
-- Выполняется вручную в DBeaver / psql под пользователем с правами DDL.
-- Подключитесь к базе tgk_bd перед запуском.

CREATE TABLE IF NOT EXISTS "Users" (
    "Id" uuid NOT NULL,
    "Email" character varying(320) NOT NULL,
    "PasswordHash" text NOT NULL,
    "IsEmailConfirmed" boolean NOT NULL,
    "EmailConfirmationToken" character varying(128) NULL,
    "EmailConfirmationTokenExpiresAt" timestamp with time zone NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Users_Email" ON "Users" ("Email");

CREATE TABLE IF NOT EXISTS "News" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" character varying(500) NOT NULL,
    "Content" text NOT NULL,
    CONSTRAINT "PK_News" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Products" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "Description" character varying(1200) NOT NULL,
    "PriceRub" numeric(14,2) NOT NULL,
    CONSTRAINT "PK_Products" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "UserAccounts" (
    "UserId" uuid NOT NULL,
    "BalanceRub" numeric(14,2) NOT NULL DEFAULT 0,
    "DebtRub" numeric(14,2) NOT NULL DEFAULT 0,
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_UserAccounts" PRIMARY KEY ("UserId"),
    CONSTRAINT "FK_UserAccounts_Users_UserId"
        FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "Contracts" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "ProductId" integer NOT NULL,
    "ContractNumber" character varying(50) NOT NULL,
    "AmountRub" numeric(14,2) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "EffectiveFrom" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Contracts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Contracts_Users_UserId"
        FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Contracts_Products_ProductId"
        FOREIGN KEY ("ProductId") REFERENCES "Products"("Id") ON DELETE RESTRICT
);
ALTER TABLE "Contracts" DROP COLUMN IF EXISTS "Status";
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Contracts_ContractNumber" ON "Contracts" ("ContractNumber");
CREATE INDEX IF NOT EXISTS "IX_Contracts_UserId" ON "Contracts" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_Contracts_ProductId" ON "Contracts" ("ProductId");

CREATE TABLE IF NOT EXISTS "BalanceTransactions" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Type" character varying(50) NOT NULL,
    "Description" character varying(200) NOT NULL,
    "AmountRub" numeric(14,2) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_BalanceTransactions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_BalanceTransactions_Users_UserId"
        FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "IX_BalanceTransactions_UserId" ON "BalanceTransactions" ("UserId");

-- Дозаполняем личные счета для существующих пользователей
INSERT INTO "UserAccounts" ("UserId", "BalanceRub", "DebtRub", "UpdatedAt")
SELECT u."Id", 0, 0, NOW()
FROM "Users" u
LEFT JOIN "UserAccounts" a ON a."UserId" = u."Id"
WHERE a."UserId" IS NULL;

-- Каталог (4 фиксированных услуги)
INSERT INTO "Products" ("Name", "Description", "PriceRub")
SELECT 'Подключение отопления', 'Оформление технических условий и подключение объекта к системе теплоснабжения.', 120000
WHERE NOT EXISTS (SELECT 1 FROM "Products" WHERE "Name" = 'Подключение отопления');
INSERT INTO "Products" ("Name", "Description", "PriceRub")
SELECT 'Оптовая электроэнергия', 'Подбор и сопровождение оптового договора поставки для предприятий.', 285000
WHERE NOT EXISTS (SELECT 1 FROM "Products" WHERE "Name" = 'Оптовая электроэнергия');
INSERT INTO "Products" ("Name", "Description", "PriceRub")
SELECT 'Тепловая энергия', 'Заключение договора на поставку тепловой энергии и контроль параметров.', 98000
WHERE NOT EXISTS (SELECT 1 FROM "Products" WHERE "Name" = 'Тепловая энергия');
INSERT INTO "Products" ("Name", "Description", "PriceRub")
SELECT 'Консультация', 'Экспертная консультация по расчетам, тарифам и технологическому присоединению.', 7500
WHERE NOT EXISTS (SELECT 1 FROM "Products" WHERE "Name" = 'Консультация');

-- Новости (6 тематических публикаций)
--DELETE FROM "News" WHERE "Title" IN ('Добро пожаловать', 'Стек');

INSERT INTO "News" ("Title", "Content")
SELECT 'Тарифы на тепловую энергию обновлены с 1 июля 2026 года',
       'В связи с изменением затрат на топливо и обслуживание сетей утверждено плановое повышение тарифов. Подробные значения доступны в личном кабинете.'
WHERE NOT EXISTS (SELECT 1 FROM "News" WHERE "Title" = 'Тарифы на тепловую энергию обновлены с 1 июля 2026 года');
INSERT INTO "News" ("Title", "Content")
SELECT 'Строительство новой котельной в промышленной зоне',
       'Начаты строительно-монтажные работы по новому энергетическому объекту. Запуск первой очереди запланирован на IV квартал.'
WHERE NOT EXISTS (SELECT 1 FROM "News" WHERE "Title" = 'Строительство новой котельной в промышленной зоне');
INSERT INTO "News" ("Title", "Content")
SELECT 'Публичный отчет ТГК-2 за 2025 год',
       'Опубликованы ключевые показатели: объем отпуска тепла, динамика подключений и инвестиции в модернизацию инфраструктуры.'
WHERE NOT EXISTS (SELECT 1 FROM "News" WHERE "Title" = 'Публичный отчет ТГК-2 за 2025 год');
INSERT INTO "News" ("Title", "Content")
SELECT 'Модернизация магистральных тепловых сетей',
       'В рамках ремонтной кампании выполняется замена изношенных участков трубопроводов для снижения теплопотерь.'
WHERE NOT EXISTS (SELECT 1 FROM "News" WHERE "Title" = 'Модернизация магистральных тепловых сетей');
INSERT INTO "News" ("Title", "Content")
SELECT 'Расширены окна подачи заявок на подключение',
       'Для клиентов открыт дополнительный период приема документов по технологическому присоединению в электронном виде.'
WHERE NOT EXISTS (SELECT 1 FROM "News" WHERE "Title" = 'Расширены окна подачи заявок на подключение');
INSERT INTO "News" ("Title", "Content")
SELECT 'План профилактических работ на осенний период',
       'Сформирован график плановых отключений и профилактики оборудования. Рекомендуем заранее проверить активные договоры.'
WHERE NOT EXISTS (SELECT 1 FROM "News" WHERE "Title" = 'План профилактических работ на осенний период');
